export const apiPathes = {
	// MAIN: "http://192.168.1.114:8003/api/v0/",
	MAIN: "http://185.176.34.207:8003/api/v0/",
	// MAIN: "http://192.168.1.178:8000/api/v0/",
	AUTH: "accounts/",
	RESET_VERIFY: "reset/verify",
	RESET: "reset/",
	UPDATE_PROFILE: "profile/update",
	UPDATE_PASSWORD: "profile/update/password",
	SIGN_IN_PASSWORD: "signin/password",
	SIGN_IN_PHONENUMBER: "signin/phonenumber",
	SIGN_IN_VERIFY: "signin/verify",
	SIGN_UP: "signup/",
	SIGN_UP_VERIFY: "signup/verify",
	BOOKMARKS: "bookmark",
	DELETE_BOOKMARK: "bookmark/",
	CATEGORIES: "shop/categories/",
	CATEGORIES_FULL: "shop/category/full",
	SHOP_PRODUCTS: "shop/products/",
	ADDRESSES: "shop/user/addresses/",
	DELETE_ADDRESS: "shop/user/address/",
	GET_PROVINCE: "shop/province/",
	GET_CATEGORY_PRODUCTS: "shop/category/",
	SEARCH: "search",
	PRODUCT_DETAILS: "shop/product/",
	NEW_COMMENT: "comment/",
	GET_COMMENTS: `comment/`,
	ADD_PRODUCT_TO_CART: "shop/cart/",
	GET_CART: "shop/cart",
	GET_CART_INFO: "shop/cart/info",
	FILTER: "shop/filter",
	PAYMENT: "payment/request/",
	BANNERS: "shop/banners/",
	SCORE: "shop/score/",
	CART_COUNT: "shop/cart/info/count",
	DELIVERY_STATUS: "shop/delivery/",
	COMPELETE: "payment/order/complete/",
	PROGRESS: "payment/order/progress/",
	PENDING: "shop/cart/pending/",
	BUY_PENDINGS: "payment/request/pendings/",
	GET_ORDER: "payment/order/complete/",
	GET_NEW_TOKEN: "access/",
}
